apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:

- target: ## NameSpace Creation
    kind: Namespace
    name: template
  patch: |-                   
    - op: replace
      path: /metadata/name
      value: namespace03

- target: ## Quota Creation
    kind: ResourceQuota
    name: template-quota
  patch: |-                   
    - op: replace
      path: /metadata/name
      value: namespace03-quota

- target: ## Quota Creation
    kind: ResourceQuota
    name: template-quota
  patch: |-                   
    - op: replace
      path: /metadata/namespace
      value: namespace03

- target: ## Quota Creation
    kind: ResourceQuota
    name: template-quota
  patch: |-                   
    - op: replace
      path: /spec/hard/requests.cpu
      value: 6

- target: ## Quota Creation
    kind: ResourceQuota
    name: template-quota
  patch: |-                   
    - op: replace
      path: /spec/hard/requests.memory
      value: 12

resources:
- ../base