apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:

- target: ## NameSpace Creation
    kind: Namespace
    name: template
  patch: |-                   
    - op: replace
      path: /metadata/name
      value: namespace01

- target: ## Quota Creation
    kind: ResourceQuota
    name: template-quota
  patch: |-                   
    - op: replace
      path: /metadata/name
      value: namespace01-quota

- target: ## Quota Creation
    kind: ResourceQuota
    name: template-quota
  patch: |-                   
    - op: replace
      path: /metadata/namespace
      value: namespace01

bases:
- ../base